// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJQmV-r-bE17bV4fYZAjVrb5X1sqhfFc',
    appId: '1:1061855145295:android:4fb7240ff47cb3db8d293a',
    messagingSenderId: '1061855145295',
    projectId: 'flutter-instagram-clone-35698',
    storageBucket: 'flutter-instagram-clone-35698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ZfA6tXdmBli83IgUZ7Vmu2ZzXGU5k5k',
    appId: '1:1061855145295:ios:f62d089a833bcc4c8d293a',
    messagingSenderId: '1061855145295',
    projectId: 'flutter-instagram-clone-35698',
    storageBucket: 'flutter-instagram-clone-35698.appspot.com',
    iosClientId: '1061855145295-qvkt4fg82gvl82jn2vjhv97i2k54d9gs.apps.googleusercontent.com',
    iosBundleId: 'com.kitety.flutterInstagramClone.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ZfA6tXdmBli83IgUZ7Vmu2ZzXGU5k5k',
    appId: '1:1061855145295:ios:f62d089a833bcc4c8d293a',
    messagingSenderId: '1061855145295',
    projectId: 'flutter-instagram-clone-35698',
    storageBucket: 'flutter-instagram-clone-35698.appspot.com',
    iosClientId: '1061855145295-qvkt4fg82gvl82jn2vjhv97i2k54d9gs.apps.googleusercontent.com',
    iosBundleId: 'com.kitety.flutterInstagramClone.stg',
  );
}
