// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCvDMNu1z7FtWsTUs6-vDNzvAwNFDeXs8',
    appId: '1:767205743715:android:93c8f77a302853edee6c56',
    messagingSenderId: '767205743715',
    projectId: 'flutter-instagram-clone-f7e4b',
    storageBucket: 'flutter-instagram-clone-f7e4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEOD-nPpR1mPggwGh3sFU95ciZikt8Pdo',
    appId: '1:767205743715:ios:1c295198a97c39d5ee6c56',
    messagingSenderId: '767205743715',
    projectId: 'flutter-instagram-clone-f7e4b',
    storageBucket: 'flutter-instagram-clone-f7e4b.appspot.com',
    iosClientId: '767205743715-6h91b0lbg8e201eh2keivu53vohm5jbr.apps.googleusercontent.com',
    iosBundleId: 'com.kitety.flutterInstagramClone.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEOD-nPpR1mPggwGh3sFU95ciZikt8Pdo',
    appId: '1:767205743715:ios:1c295198a97c39d5ee6c56',
    messagingSenderId: '767205743715',
    projectId: 'flutter-instagram-clone-f7e4b',
    storageBucket: 'flutter-instagram-clone-f7e4b.appspot.com',
    iosClientId: '767205743715-6h91b0lbg8e201eh2keivu53vohm5jbr.apps.googleusercontent.com',
    iosBundleId: 'com.kitety.flutterInstagramClone.dev',
  );
}
