// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3zlvER6aw3oIaVxMmITsNLr9vE1Ojg3Y',
    appId: '1:239491038093:android:217d962f5553d611ab9bc4',
    messagingSenderId: '239491038093',
    projectId: 'flutter-instagram-clone-fe996',
    storageBucket: 'flutter-instagram-clone-fe996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwB3ojUAF9Rf6tQ-mNUwZnf72TubT-pXo',
    appId: '1:239491038093:ios:86d5e6b4362410f8ab9bc4',
    messagingSenderId: '239491038093',
    projectId: 'flutter-instagram-clone-fe996',
    storageBucket: 'flutter-instagram-clone-fe996.appspot.com',
    iosClientId: '239491038093-qqcbvqmuj0gvf9emfgdgtfknkndn7jp2.apps.googleusercontent.com',
    iosBundleId: 'com.kitety.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwB3ojUAF9Rf6tQ-mNUwZnf72TubT-pXo',
    appId: '1:239491038093:ios:86d5e6b4362410f8ab9bc4',
    messagingSenderId: '239491038093',
    projectId: 'flutter-instagram-clone-fe996',
    storageBucket: 'flutter-instagram-clone-fe996.appspot.com',
    iosClientId: '239491038093-qqcbvqmuj0gvf9emfgdgtfknkndn7jp2.apps.googleusercontent.com',
    iosBundleId: 'com.kitety.flutterInstagramClone',
  );
}
