name: 'powersync_repository'
version: '0.1.0+1'
publish_to: none
environment: 
  sdk: '^3.4.0'
  flutter: '^3.22.0'
description: A Very Good Project created by Very Good CLI.
dependencies: 
  env: 
    path: ../env
  flutter: 
    sdk: flutter
  path: '>=1.8.3 <=1.9.0'
  path_provider: '^2.1.4'
  powersync: '^1.6.4'
  shared: 
    path: ../shared
  supabase_flutter: '^2.6.0'
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  mocktail: '^1.0.4'
  very_good_analysis: '^6.0.0'
